### ISSUE TITLE
Wrote a solver too

### ISSUE THREAD

**Issue by moritzgloeckl** [ianmcaulay/Calculator_the_Game_Solver#1]
Hey,

I just found your solver, and wrote one myself too (in Python), I'm curious how yours is working! 

P.S.: I've found one more operator, it looks like this: "1=>2" and it replaces every 1 with a 2 for example. Maybe there are more but I haven't found them yet!

**Comment by ianmcaulay** [comment]
Hi,

Thanks for commenting! I just pushed a bunch of changes (including adding the arrow operation), and it's worked on the couple example levels I've tried it on so feel free to test it out on some of your own :)

I'd be curious to know how you went about programming yours and if you have a similar structure, I think mine could definitely be improved to be a lot smarter than just trying all possible combinations of moves. 

Thanks!

**Comment by moritzgloeckl** [comment]
Hi,

looks good! Unfortunately I haven't found another way yet. Mine also works by trying all moves, although I think it's fast enough, given the low number of possible moves. I like that you're doing a recursive function, I'm generating the possible combinations with `itertools`:

`itertools.product(possibleOperators, repeat=moves)`

I've also tried to solve the problems mathematically, but haven't found out much yet. 

I'm also trying to add a way to solve it by providing a screenshot of the game, using OCR to get the parameters needed.

Is this a personal project you're working on or do you plan to do something with it?

Cheers.

**Comment by ianmcaulay** [comment]
Using OCR would be super cool, let me know if you make any progress on that. The way I have it implemented now requires calling a function so someone would probably have to be at least familiar with Python to be able to use it. If you could just feed it an OCR image and it would automatically extract the parameters that would be great though. 

It's just a project I started for fun with a friend. I probably won't do much more with it, maybe add a couple minor updates. What about you?
